name: Python Application Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: make install

    - name: Run Flask application (background)
      run: |
        nohup make run &
        sleep 10

    - name: Test server response
      run: curl --fail http://127.0.0.1:3000

    - name: Kill Flask server
      run: kill $(jobs -p)
